<a href="https://colab.research.google.com/github/yongug/Fly_python/blob/main/fly_ai_4_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iris(붓꽃) 머신러닝 예제 ( Decision Tree)

In [1]:
!pip install pandas
!pip install numpy
!pip install sklearn


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
# 모듈 로딩

# 내장 붓꽃 데이터셋
from sklearn.datasets import load_iris
# 의사결정트리 모델
from sklearn.tree import DecisionTreeClassifier
# 데이터셋 분리 함수
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
#(2) 붓꽃 데이터 셋 로딩
iris = load_iris()
# 딕셔너리 형태
print(type(iris))
iris

<class 'sklearn.utils._bunch.Bunch'>


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
#(2) 붓꽃 데이터 셋 로딩
# data: 4개의 피처(feature)들로 이루어진 numpy 배열
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
# target: 붓꽃 데이터셋의 레이블(결정 값) 데이터로 된 numpy배열
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [6]:
# 붓꽃 데이터셋을 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data,
columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
# 레이블 컬럼 추가
iris_df['label'] = iris_label
print(iris_df)
iris_df.head(3)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [8]:
#(3) 학습데이터/ 테스트 데이터 분리
# 데이터셋의 20%를 테스트 데이터로 사용
X_train, X_test, y_train, y_test = train_test_split(
iris_data,
iris_label,
test_size=0.2,
random_state=11
)

In [9]:
#(4) 학습데이터셋으로 학습(Train)
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [11]:
#(5) 테스트 데이터셋으로 예측(Predict)
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [12]:
#(6) 예측 정확도 평가(accuracy_score)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


# **스마트 팩토리 제품 품질 상태분류**

In [93]:
!pip install pandas
!pip install numpy
!pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [161]:
# 모듈 로딩

# 의사결정트리 모델
from sklearn.tree import DecisionTreeClassifier
# 데이터셋 분리 함수
from sklearn.model_selection import train_test_split
import pandas as pd

In [162]:
test = pd.read_csv('./test.csv')
train = pd.read_csv('./train.csv')

In [40]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Columns: 2879 entries, PRODUCT_ID to X_2875
dtypes: float64(2875), object(4)
memory usage: 6.8+ MB


In [41]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Columns: 2881 entries, PRODUCT_ID to X_2875
dtypes: float64(2876), int64(1), object(4)
memory usage: 13.1+ MB


In [18]:
test.head()

PRODUCT_ID         TIMESTAMP     LINE PRODUCT_CODE  X_1   X_2  X_3   X_4  \
0   TEST_000   2022-09-09 2:01  T100306         T_31  2.0  94.0  0.0  45.0   
1   TEST_001   2022-09-09 2:09  T100304         T_31  2.0  93.0  0.0  45.0   
2   TEST_002   2022-09-09 8:42  T100304         T_31  2.0  95.0  0.0  45.0   
3   TEST_003  2022-09-09 10:56  T010305         A_31  NaN   NaN  NaN   NaN   
4   TEST_004  2022-09-09 11:04  T010306         A_31  NaN   NaN  NaN   NaN   

    X_5  X_6  ...  X_2866  X_2867  X_2868  X_2869  X_2870  X_2871  X_2872  \
0  10.0  0.0  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1  11.0  0.0  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2  11.0  0.0  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3   NaN  NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4   NaN  NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

   X_2873  X_2874  X_2875  
0     NaN     NaN     NaN  
1     NaN     NaN     NaN  
2     NaN     NaN     NaN  
3     NaN     NaN     NaN  
4     NaN     NaN     NaN  

[5 rows x 2879 columns]

In [19]:
train.head()

PRODUCT_ID  Y_Class  Y_Quality        TIMESTAMP     LINE PRODUCT_CODE  X_1  \
0  TRAIN_000        1   0.533433  2022-06-13 5:14  T050304         A_31  NaN   
1  TRAIN_001        2   0.541819  2022-06-13 5:22  T050307         A_31  NaN   
2  TRAIN_002        1   0.531267  2022-06-13 5:30  T050304         A_31  NaN   
3  TRAIN_003        2   0.537325  2022-06-13 5:39  T050307         A_31  NaN   
4  TRAIN_004        1   0.531590  2022-06-13 5:47  T050304         A_31  NaN   

   X_2  X_3  X_4  ...  X_2866  X_2867  X_2868  X_2869  X_2870  X_2871  X_2872  \
0  NaN  NaN  NaN  ...   39.34   40.89   32.56   34.09   77.77     NaN     NaN   
1  NaN  NaN  NaN  ...   38.89   42.82   43.92   35.34   72.55     NaN     NaN   
2  NaN  NaN  NaN  ...   39.19   36.65   42.47   36.53   78.35     NaN     NaN   
3  NaN  NaN  NaN  ...   37.74   39.17   52.17   30.58   71.78     NaN     NaN   
4  NaN  NaN  NaN  ...   38.70   41.89   46.93   33.09   76.97     NaN     NaN   

   X_2873  X_2874  X_2875  
0     NaN     NaN     NaN  
1     NaN     NaN     NaN  
2     NaN     NaN     NaN  
3     NaN     NaN     NaN  
4     NaN     NaN     NaN  

[5 rows x 2881 columns]

In [163]:
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('train.csv')

# X_1에 값이 있는 행만 선택
data_filtered = data[data['X_1'].notna()]

# 사용할 feature 선택 (product_code와 의미 있는 X_변수 9개)
features = ['X_1', 'X_2', 'X_4', 'X_5', 'X_7']

# 선택한 feature만 추출
selected_data = data_filtered[features]

# numpy 배열로 변환
selected_array = selected_data.to_numpy()

# 결과 출력
print(selected_array)
selected_array

[[  2. 102.  45.  11.  45.]
 [  2. 102.  45.  11.  45.]
 [  2.  97.  45.  11.  45.]
 ...
 [  2.  95.  45.  10.  50.]
 [ 40.  94.  45.  11.  45.]
 [ 21.  87.  45.  10.  61.]]


array([[  2., 102.,  45.,  11.,  45.],
       [  2., 102.,  45.,  11.,  45.],
       [  2.,  97.,  45.,  11.,  45.],
       ...,
       [  2.,  95.,  45.,  10.,  50.],
       [ 40.,  94.,  45.,  11.,  45.],
       [ 21.,  87.,  45.,  10.,  61.]])

In [164]:
# 라벨 추출

data_label = data_filtered['Y_Class']
data_label

22     0
23     0
25     1
26     1
29     1
      ..
591    1
592    1
593    1
596    1
597    1
Name: Y_Class, Length: 349, dtype: int64

In [165]:
# 스마트 팩토리 데이터 셋을 자세히 보기 위해 DataFrame으로 변환
data_df = pd.DataFrame(data=selected_array,
columns=features)
data_df

X_1    X_2   X_4   X_5   X_7
0     2.0  102.0  45.0  11.0  45.0
1     2.0  102.0  45.0  11.0  45.0
2     2.0   97.0  45.0  11.0  45.0
3     2.0   95.0  45.0  10.0  54.0
4     2.0  100.0  45.0  11.0  45.0
..    ...    ...   ...   ...   ...
344   1.0   87.0  45.0  10.0  50.0
345   2.0   98.0  45.0  10.0  45.0
346   2.0   95.0  45.0  10.0  50.0
347  40.0   94.0  45.0  11.0  45.0
348  21.0   87.0  45.0  10.0  61.0

[349 rows x 5 columns]

In [166]:
# 레이블 컬럼 추가

data_df['label'] = data_label
print(data_df)
data_df.head(3)


      X_1    X_2   X_4   X_5   X_7  label
0     2.0  102.0  45.0  11.0  45.0    NaN
1     2.0  102.0  45.0  11.0  45.0    NaN
2     2.0   97.0  45.0  11.0  45.0    NaN
3     2.0   95.0  45.0  10.0  54.0    NaN
4     2.0  100.0  45.0  11.0  45.0    NaN
..    ...    ...   ...   ...   ...    ...
344   1.0   87.0  45.0  10.0  50.0    NaN
345   2.0   98.0  45.0  10.0  45.0    1.0
346   2.0   95.0  45.0  10.0  50.0    NaN
347  40.0   94.0  45.0  11.0  45.0    1.0
348  21.0   87.0  45.0  10.0  61.0    2.0

[349 rows x 6 columns]


X_1    X_2   X_4   X_5   X_7  label
0  2.0  102.0  45.0  11.0  45.0    NaN
1  2.0  102.0  45.0  11.0  45.0    NaN
2  2.0   97.0  45.0  11.0  45.0    NaN

In [167]:
#(3) 학습데이터/ 테스트 데이터 분리
# 데이터셋의 20%를 테스트 데이터로 사용

X_train, X_test, y_train, y_test = train_test_split(
selected_array,
data_label,
test_size=0.2,
random_state=11
)

In [168]:
#(4) 학습데이터셋으로 학습(Train)
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [169]:
#(5) 테스트 데이터셋으로 예측(Predict)
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1])

In [170]:
#(6) 예측 정확도 평가(accuracy_score)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.8429


# **교차검증**

In [171]:
#(1) 라이브러리 로드와 데이터셋 로딩
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

# 붓꽃 데이터셋 호출
iris = load_iris()
features = iris.data
label = iris.target

features_smart = selected_array
label_smart = data_label


In [172]:
# (2) 의사결정 트리 모델 객체 생성
# 의사결정트리 모델 객체 생성
dt_clf = DecisionTreeClassifier()
# 5개의 폴드 세트로 분리하는 KFold 객체 생성
kfold = KFold(n_splits=5)
# 폴드 세트별 정확도를 담을 리스트 객체 생성
cv_accuracy = []
#반복횟수 확인용
n_iter = 0

In [173]:
# (2) 의사결정 트리 모델 객체 생성
# 의사결정트리 모델 객체 생성
dt_clf = DecisionTreeClassifier()
# 5개의 폴드 세트로 분리하는 KFold 객체 생성
kfold = KFold(n_splits=5)
# 폴드 세트별 정확도를 담을 리스트 객체 생성
cv_accuracy = []
#반복횟수 확인용
n_iter = 0

In [174]:
# (3) 교차검증
# KFold 객체의 split() 호출하면 폴드 별 학습용, 검증용 테스트의 row 인덱스를 array로 반환
for train_index, test_index in kfold.split(features_smart):
 # kfold.split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
 X_train, X_test = features_smart[train_index], features_smart[test_index]
 # Use .iloc to access elements by position
 y_train, y_test = label_smart.iloc[train_index], label_smart.iloc[test_index]

 #학습 및 예측
 dt_clf.fit(X_train, y_train)
 pred = dt_clf.predict(X_test)
 n_iter += 1

 # 반복 시 마다 정확도 측정
 accuracy = np.round(accuracy_score(y_test,pred), 4)
 train_size = X_train.shape[0]
 test_size = X_test.shape[0]
 print('\\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
 .format(n_iter, accuracy, train_size, test_size))
 print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))

 cv_accuracy.append(accuracy)

\n#1 교차 검증 정확도 :0.8143, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
\n#2 교차 검증 정확도 :0.8429, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#2 검증 세트 인덱스:[ 70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105
 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123
 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139]
\n#3 교차 검증 정확도 :0.7571, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#3 검증 세트 인덱스:[140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209]
\n#4 교차 검증 정확도 

In [175]:
# (3) 교차검증
# KFold 객체의 split() 호출하면 폴드 별 학습용, 검증용 테스트의 row 인덱스를 array로 반환
for train_index, test_index in kfold.split(features_smart):
 # kfold.split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
 X_train, X_test = features_smart[train_index], features_smart[test_index]
 y_train, y_test = label_smart.iloc[train_index], label_smart.iloc[test_index]

 #학습 및 예측
 dt_clf.fit(X_train, y_train)
 pred = dt_clf.predict(X_test)
 n_iter += 1

 # 반복 시 마다 정확도 측정
 accuracy = np.round(accuracy_score(y_test,pred), 4)
 train_size = X_train.shape[0]
 test_size = X_test.shape[0]
 print('\\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
 .format(n_iter, accuracy, train_size, test_size))
 print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))

 cv_accuracy.append(accuracy)

\n#6 교차 검증 정확도 :0.8143, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#6 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
\n#7 교차 검증 정확도 :0.8429, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#7 검증 세트 인덱스:[ 70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105
 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123
 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139]
\n#8 교차 검증 정확도 :0.7571, 학습 데이터 크기: 279, 검증 데이터 크기: 70
#8 검증 세트 인덱스:[140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209]
\n#9 교차 검증 정확도 

In [176]:
# (4) 정확도
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\\n## 평균 검증 정확도:', np.mean(cv_accuracy))

\n## 평균 검증 정확도: 0.78464


불균형한 레이블 분포도를 가진 데이터셋을 위한 K폴드 방식
학습 데이터와 검증 데이터 세트가 가지는 레이블 분포도가 유사하도록 폴드세트를 구성.
예를 들어 신용카드 사기를 잡아내야 하는데 그 비율이 100건 중 10건이라면, 어떤 데이터셋에는 사
기인 경우가 하나도 없고 어떤 데이터셋에는 사기인 레이블이 몰려있지 않도록 폴드세트의 레이블 구
성 비율을 동일하게 나눔.
대부분 분류 모델의 경우 stratified k-fold를 사용하는 것이 좋음

In [177]:
# Stratified K-Fold
# (1) 라이브러리
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

In [178]:
# (2) 데이터셋 로딩
# 붓꽃 데이터셋 호출
iris = load_iris()
features = iris.data
label = iris.target

features_smart = selected_array
label_smart = data_label

# 레이블 분포 확인
data_df = pd.DataFrame(data=features_smart,columns=features)



data_df['label']=label_smart
data_df['label'].value_counts() # 0:50, 1:50, 2:50




ValueError: Index data must be 1-dimensional

In [180]:
# (2) 데이터셋 로딩
# 붓꽃 데이터셋 호출
iris = load_iris()
features = iris.data
label = iris.target

features_smart = selected_array
label_smart = data_label

# 레이블 분포 확인
# Use the feature names from the iris dataset (assuming they match the columns in features_smart)
feature_names = iris.feature_names
data_df = pd.DataFrame(data=features_smart, columns=features)

data_df['label'] = label_smart
data_df['label'].value_counts()  # 0:50, 1:50, 2:50

ValueError: Index data must be 1-dimensional

In [139]:
# (3) 3개의 폴드셋트 객체 생성
# 3개의 폴드세트로 나누는 Stratified K-Fold 객체 생성
skf = StratifiedKFold(n_splits=3)
# 반복횟수 확인용
n_iter=0
# 데이터셋 별 레이블 분포 확인 -> 균등한 비율로 분포가 된 것을 확인가능
for train_index, test_index in skf.split(iris_df, iris_df['label']):
 n_iter += 1
 label_train= iris_df['label'].iloc[train_index]
 label_test= iris_df['label'].iloc[test_index]
 print('## 교차 검증: {0}'.format(n_iter))
 print('학습 레이블 데이터 분포:\\n', label_train.value_counts())
 print('검증 레이블 데이터 분포:\\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:\n label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:\n label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:\n label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
1    17
2    17
0    16
Name: count, dtype: int64


In [140]:
# (3) 의사결정트리 모델 객체 생성
# 의사결정트리 모델 객체 생성
dt_clf = DecisionTreeClassifier()
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

In [141]:
# (4) 학습용/검증용 데이터 분리
# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 셋도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
 # split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
 X_train, X_test = features[train_index], features[test_index]
 y_train, y_test = label[train_index], label[test_index]

 #학습 및 예측
 dt_clf.fit(X_train , y_train)
 pred = dt_clf.predict(X_test)
 # 반복 시 마다 정확도 측정
 n_iter += 1
 accuracy = np.round(accuracy_score(y_test,pred), 4)
 train_size = X_train.shape[0]
 test_size = X_test.shape[0]

 print('\\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
 .format(n_iter, accuracy, train_size, test_size))
 print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
 cv_accuracy.append(accuracy)

\n#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
\n#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
\n#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [142]:
#(4) 학습용/검증용 데이터 분리
# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 셋도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
 # split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
 X_train, X_test = features[train_index], features[test_index]
 y_train, y_test = label[train_index], label[test_index]

In [143]:
#(5) 정확도
# 교차 검증별 정확도 및 평균 정확도 계산
print('\\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))

\n## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


cross_val_score()
교차검증을 보다 간편하게 해주는 API. 위에서 했던 for문을 통한 반복
을 생략시켜준다.
주요 파라미터
estimator : 분류/회귀 모델 객체
X : 피처 데이터셋
y : 레이블 데이터셋
scoring : 평가기준 (평균, 정확도 등)
cv : 교차검증 횟수
from sklearn.tree impor

# **cross_val_score**

In [144]:
# (1) 라이브러리 호출
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

In [145]:
# (2) 데이터셋 로딩
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
dt_clf

DecisionTreeClassifier(random_state=156)

In [146]:
# (3) 피처 데이터셋
# 피처 데이터셋
data = iris_data.data
# 레이블 데이터셋
label = iris_data.target
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [147]:
#(4) 정확도, 교차검증 셋 3개
# 성능 지표는 정확도(accuracy) , 교차 검증 세트는 3개
scores = cross_val_score(dt_clf , data , label ,
scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


# **교차검증 - 스마트 팩토리 제품 검증**